{% set name = "python-slugify" %}
{% set version = "3.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7dda1c0d7f9ff85c405be412d53b842015db18e32b598d46a805546bc1a66a5b
  patches:
      - fix_command.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - slugify = slugify.cli:main

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - text-unidecode 1.2
    - unidecode >=0.04.16

test:
  imports:
    - slugify

  source_files:
    - test.py

  commands:
    - slugify --help
    - python test.py


about:
  home: https://github.com/un33k/python-slugify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Python Slugify application that handles Unicode'
  dev_url: https://github.com/un33k/python-slugify

extra:
  recipe-maintainers:
    - proinsias
    - sodre
